global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmniindiadistro
  name: hiu-ui
  tag: latest

service:
  type: ClusterIP
  port: 5000

config:
  BACKEND_BASE_URL: ""
  BASE_NAME: '/hiuser'
  BACKEND_API_PATH: "/hiu-api"
  DICOM_SERVER_PATH: '/'
  VIEWER_PAGE: "/viewer/"
  TITLE: "HIU"
  TIMEZONE_OFFSET: "+05:30"


autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
