name: Release build

on:
  push:
    tags:
      - uat-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Get the version
        run: echo 'Release version' $RELEASE_VERSION
      - name: NHA Docker Registry
        env:
          DOCKER_REGISTRY_URL: docker.io
          NHA_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NHA_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker login -u $NHA_USERNAME -p $NHA_PASSWORD $DOCKER_REGISTRY_URL
      - name: Build docker image for NHA
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NHA_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker build -t $NHA_USERNAME/$CONTAINER_REPO_NAME:$RELEASE_VERSION .
      - name: Push Docker image to NHA Registry
        env:
          CONTAINER_REPO_NAME: hiu-ui
          NHA_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: docker push $NHA_USERNAME/$CONTAINER_REPO_NAME:$RELEASE_VERSION
